// <auto-generated />
using System;
using Booking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250226205827_123")]
    partial class _123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Free Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gym/Fitness Center"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Restaurant"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bar/Lounge"
                        },
                        new
                        {
                            Id = 8,
                            Name = "24/7 Room Service"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Spa & Wellness Center"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Conference Room"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Airport Shuttle"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Business Center"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Breakfast Included"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pet-Friendly"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Laundry Service"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Non-Smoking Rooms"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Children's Playground"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Jacuzzi/Hot Tub"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Private Beach Access"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Car Rental Service"
                        });
                });

            modelBuilder.Entity("Booking.Models.AmenityRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequsetStatus")
                        .HasColumnType("int");

                    b.Property<int>("RoomClassId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomClassId");

                    b.ToTable("AmenityRequests");
                });

            modelBuilder.Entity("Booking.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "sec");

                    b.HasData(
                        new
                        {
                            Id = "8709e6d5-6c9e-442e-98d6-49d39f80014f",
                            AccessFailedCount = 0,
                            AvatarUrl = "/assets/images/avatar/PlaceHolder.png",
                            CityId = 1,
                            ConcurrencyStamp = "8f569d50-58aa-4099-94b7-68a7cbd8ba41",
                            DOB = new DateOnly(2004, 1, 10),
                            Email = "Mohammadabuaisheh40@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mohammad",
                            JoinDate = new DateTime(2025, 2, 26, 23, 58, 26, 624, DateTimeKind.Local).AddTicks(6109),
                            LastName = "Abu Aisheh",
                            LockoutEnabled = false,
                            NormalizedEmail = "MOHAMMADABUAISHEH40@GMAIL.COM",
                            NormalizedUserName = "MOHAMMAD",
                            PasswordHash = "AQAAAAIAAYagAAAAEDLsGpWQqGNUGY/bCKJFJQnGeUARgIEKmxiP0gGRLfq2lOULTF0m7rCfG3MU0TUt0Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f73eb42e-7153-44a4-8a5e-aa8f5d0b184c",
                            TwoFactorEnabled = false,
                            UserName = "Mohammad"
                        });
                });

            modelBuilder.Entity("Booking.Models.Blogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Booking.Models.BookingRoom", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("BookingRooms");
                });

            modelBuilder.Entity("Booking.Models.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Booking.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VisitCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            ImageUrl = "riyadh.jpg",
                            Name = "Riyadh",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            ImageUrl = "jeddah.jpg",
                            Name = "Jeddah",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            ImageUrl = "mecca.jpg",
                            Name = "Mecca",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            ImageUrl = "medina.jpg",
                            Name = "Medina",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            ImageUrl = "dubai.jpg",
                            Name = "Dubai",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            ImageUrl = "abudhabi.jpg",
                            Name = "Abu Dhabi",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            ImageUrl = "doha.jpg",
                            Name = "Doha",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 4,
                            ImageUrl = "kuwait.jpg",
                            Name = "Kuwait City",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 5,
                            ImageUrl = "muscat.jpg",
                            Name = "Muscat",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 6,
                            ImageUrl = "manama.jpg",
                            Name = "Manama",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 7,
                            ImageUrl = "cairo.jpg",
                            Name = "Cairo",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 7,
                            ImageUrl = "alexandria.jpg",
                            Name = "Alexandria",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 8,
                            ImageUrl = "amman.jpg",
                            Name = "Amman",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 9,
                            ImageUrl = "beirut.jpg",
                            Name = "Beirut",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 10,
                            ImageUrl = "istanbul.jpg",
                            Name = "Istanbul",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 10,
                            ImageUrl = "ankara.jpg",
                            Name = "Ankara",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 11,
                            ImageUrl = "marrakech.jpg",
                            Name = "Marrakech",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 11,
                            ImageUrl = "casablanca.jpg",
                            Name = "Casablanca",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 12,
                            ImageUrl = "tunis.jpg",
                            Name = "Tunis",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 13,
                            ImageUrl = "algiers.jpg",
                            Name = "Algiers",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 14,
                            ImageUrl = "newyork.jpg",
                            Name = "New York",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 14,
                            ImageUrl = "losangeles.jpg",
                            Name = "Los Angeles",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 15,
                            ImageUrl = "london.jpg",
                            Name = "London",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 16,
                            ImageUrl = "paris.jpg",
                            Name = "Paris",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 17,
                            ImageUrl = "berlin.jpg",
                            Name = "Berlin",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 18,
                            ImageUrl = "toronto.jpg",
                            Name = "Toronto",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 19,
                            ImageUrl = "sydney.jpg",
                            Name = "Sydney",
                            VisitCount = 0
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 20,
                            ImageUrl = "tokyo.jpg",
                            Name = "Tokyo",
                            VisitCount = 0
                        });
                });

            modelBuilder.Entity("Booking.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 14,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 15,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 16,
                            Name = "France"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Japan"
                        });
                });

            modelBuilder.Entity("Booking.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Booking.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Booking.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Booking.Models.JoinUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfSubmission")
                        .HasColumnType("datetime2");

                    b.Property<string>("GovermentCertificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityProof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerShipProof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JoinUs");
                });

            modelBuilder.Entity("Booking.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvgRoomSize")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JoinUsId")
                        .HasColumnType("int");

                    b.Property<int>("ListingTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<decimal>("StarterPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalFloor")
                        .HasColumnType("int");

                    b.Property<int>("TotalRoom")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CityId");

                    b.HasIndex("JoinUsId")
                        .IsUnique()
                        .HasFilter("[JoinUsId] IS NOT NULL");

                    b.HasIndex("ListingTypeId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Booking.Models.ListingImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("Booking.Models.ListingRoomClass", b =>
                {
                    b.Property<int>("RoomClassId")
                        .HasColumnType("int");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.HasKey("RoomClassId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingRoomClasses");
                });

            modelBuilder.Entity("Booking.Models.ListingService", b =>
                {
                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("ListingId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ListingServices");
                });

            modelBuilder.Entity("Booking.Models.ListingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ListingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Luxury Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resort"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Business Hotel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Boutique Hotel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Budget Hotel"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hostel"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bed & Breakfast"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Apartment Hotel"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Extended Stay Hotel"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Eco-Friendly Hotel"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Historic Hotel"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Motel"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Capsule Hotel"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Beachfront Hotel"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ski Resort"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Casino Hotel"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Waterpark Resort"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Wellness & Spa Hotel"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Guesthouse"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Floating Hotel"
                        });
                });

            modelBuilder.Entity("Booking.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AgentReplyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Booking.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdultsCapacity")
                        .HasColumnType("int");

                    b.Property<int>("BookedCount")
                        .HasColumnType("int");

                    b.Property<int>("ChildrenCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomClassId")
                        .HasColumnType("int");

                    b.Property<string>("RoomNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("RoomClassId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Booking.Models.RoomClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("RoomClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single Room"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Double Room"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Triple Room"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quad Room"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Queen Room"
                        },
                        new
                        {
                            Id = 6,
                            Name = "King Room"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hollywood Twin Room"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Suite"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Family Room"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Connected Room"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Delux Room"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Executive Room"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Presidential Suite"
                        });
                });

            modelBuilder.Entity("Booking.Models.RoomClassAmenity", b =>
                {
                    b.Property<int>("RoomClassId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("AmenityId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.HasKey("RoomClassId", "AmenityId", "ListingId");

                    b.HasIndex("AmenityId");

                    b.HasIndex("ListingId");

                    b.ToTable("RoomClassAmenities");
                });

            modelBuilder.Entity("Booking.Models.RoomImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages");
                });

            modelBuilder.Entity("Booking.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "English-speaking staff",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Spanish-speaking staff",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "French-speaking staff",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "German-speaking staff",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Guided City Tours",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hiking Trips",
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Scuba Diving Classes",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Cultural Workshops",
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Credit Card Accepted",
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "PayPal Accepted",
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            Description = "Apple Pay Accepted",
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Cryptocurrency Payments",
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "24-hour Front Desk",
                            Type = 4
                        },
                        new
                        {
                            Id = 14,
                            Description = "Daily Housekeeping",
                            Type = 4
                        },
                        new
                        {
                            Id = 15,
                            Description = "Airport Pickup/Drop-off",
                            Type = 4
                        },
                        new
                        {
                            Id = 16,
                            Description = "Car Rental Service",
                            Type = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "CCTV Surveillance",
                            Type = 5
                        },
                        new
                        {
                            Id = 18,
                            Description = "Secure Lockers",
                            Type = 5
                        },
                        new
                        {
                            Id = 19,
                            Description = "Fire Extinguishers Available",
                            Type = 5
                        },
                        new
                        {
                            Id = 20,
                            Description = "24-hour Security",
                            Type = 5
                        });
                });

            modelBuilder.Entity("Booking.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequsetStatus")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "sec");

                    b.HasData(
                        new
                        {
                            Id = "f3776bee-aa31-4560-a259-03afe71b4b83",
                            ConcurrencyStamp = "6b7eda24-b7df-4b98-9e87-aa9663bb7808",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "27c0908b-e09c-4a68-906d-e42c3295dec9",
                            ConcurrencyStamp = "9b52f8d9-cfbe-4f9c-bdfb-41423f3face9",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "86343a28-20ab-450e-b401-5fa16c073688",
                            ConcurrencyStamp = "9348b5af-c885-44d5-8f55-28610173c272",
                            Name = "Agent",
                            NormalizedName = "AGENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "sec");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "sec");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "sec");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "sec");

                    b.HasData(
                        new
                        {
                            UserId = "8709e6d5-6c9e-442e-98d6-49d39f80014f",
                            RoleId = "f3776bee-aa31-4560-a259-03afe71b4b83"
                        },
                        new
                        {
                            UserId = "8709e6d5-6c9e-442e-98d6-49d39f80014f",
                            RoleId = "27c0908b-e09c-4a68-906d-e42c3295dec9"
                        },
                        new
                        {
                            UserId = "8709e6d5-6c9e-442e-98d6-49d39f80014f",
                            RoleId = "86343a28-20ab-450e-b401-5fa16c073688"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "sec");
                });

            modelBuilder.Entity("Booking.Models.AmenityRequest", b =>
                {
                    b.HasOne("Booking.Models.RoomClass", "RoomClass")
                        .WithMany()
                        .HasForeignKey("RoomClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomClass");
                });

            modelBuilder.Entity("Booking.Models.AppUser", b =>
                {
                    b.HasOne("Booking.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Booking.Models.BookingRoom", b =>
                {
                    b.HasOne("Booking.Models.Bookings", "Booking")
                        .WithMany("BookingRooms")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.Room", "Room")
                        .WithMany("BookingRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Booking.Models.Bookings", b =>
                {
                    b.HasOne("Booking.Models.Listing", "Listing")
                        .WithMany("Bookings")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.AppUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Models.City", b =>
                {
                    b.HasOne("Booking.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Booking.Models.Favorite", b =>
                {
                    b.HasOne("Booking.Models.Listing", "Listing")
                        .WithMany("Favorites")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.AppUser", "AppUser")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Booking.Models.Invoice", b =>
                {
                    b.HasOne("Booking.Models.Bookings", "Booking")
                        .WithMany("Invoices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.Room", "Room")
                        .WithMany("Invoices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Booking.Models.JoinUs", b =>
                {
                    b.HasOne("Booking.Models.AppUser", "Agent")
                        .WithMany("JoinUsRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Booking.Models.Listing", b =>
                {
                    b.HasOne("Booking.Models.AppUser", "Agent")
                        .WithMany("Listings")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booking.Models.City", "City")
                        .WithMany("Listings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.JoinUs", "JoinUs")
                        .WithOne("Listing")
                        .HasForeignKey("Booking.Models.Listing", "JoinUsId");

                    b.HasOne("Booking.Models.ListingType", "ListingType")
                        .WithMany("Listings")
                        .HasForeignKey("ListingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("City");

                    b.Navigation("JoinUs");

                    b.Navigation("ListingType");
                });

            modelBuilder.Entity("Booking.Models.ListingImage", b =>
                {
                    b.HasOne("Booking.Models.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Booking.Models.ListingRoomClass", b =>
                {
                    b.HasOne("Booking.Models.Listing", "Listing")
                        .WithMany("ListingRoomClasses")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.RoomClass", "RoomClass")
                        .WithMany("ListingRoomClasses")
                        .HasForeignKey("RoomClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("RoomClass");
                });

            modelBuilder.Entity("Booking.Models.ListingService", b =>
                {
                    b.HasOne("Booking.Models.Listing", "Listing")
                        .WithMany("ListingServices")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.Service", "Service")
                        .WithMany("ListingServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Booking.Models.Review", b =>
                {
                    b.HasOne("Booking.Models.Listing", "Listing")
                        .WithMany("Reviews")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.AppUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Models.Room", b =>
                {
                    b.HasOne("Booking.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.RoomClass", "RoomClass")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("RoomClass");
                });

            modelBuilder.Entity("Booking.Models.RoomClass", b =>
                {
                    b.HasOne("Booking.Models.Discount", null)
                        .WithMany("RoomClasses")
                        .HasForeignKey("DiscountId");
                });

            modelBuilder.Entity("Booking.Models.RoomClassAmenity", b =>
                {
                    b.HasOne("Booking.Models.Amenity", "Amenity")
                        .WithMany("RoomClassAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booking.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.RoomClass", "RoomClass")
                        .WithMany("RoomClassAmenities")
                        .HasForeignKey("RoomClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Listing");

                    b.Navigation("RoomClass");
                });

            modelBuilder.Entity("Booking.Models.RoomImage", b =>
                {
                    b.HasOne("Booking.Models.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Booking.Models.Service", b =>
                {
                    b.HasOne("Booking.Models.Listing", null)
                        .WithMany("Services")
                        .HasForeignKey("ListingId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Booking.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Booking.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Booking.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking.Models.Amenity", b =>
                {
                    b.Navigation("RoomClassAmenities");
                });

            modelBuilder.Entity("Booking.Models.AppUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("JoinUsRequests");

                    b.Navigation("Listings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Booking.Models.Bookings", b =>
                {
                    b.Navigation("BookingRooms");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Booking.Models.City", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Booking.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Booking.Models.Discount", b =>
                {
                    b.Navigation("RoomClasses");
                });

            modelBuilder.Entity("Booking.Models.JoinUs", b =>
                {
                    b.Navigation("Listing")
                        .IsRequired();
                });

            modelBuilder.Entity("Booking.Models.Listing", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("ListingRoomClasses");

                    b.Navigation("ListingServices");

                    b.Navigation("Reviews");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Booking.Models.ListingType", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Booking.Models.Room", b =>
                {
                    b.Navigation("BookingRooms");

                    b.Navigation("Images");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Booking.Models.RoomClass", b =>
                {
                    b.Navigation("ListingRoomClasses");

                    b.Navigation("RoomClassAmenities");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Booking.Models.Service", b =>
                {
                    b.Navigation("ListingServices");
                });
#pragma warning restore 612, 618
        }
    }
}
